// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package user_repository

import (
	"github.com/jackc/pgx/v5/pgtype"
)

// Пользователи
type User struct {
	ID              int64
	Name            string
	Email           string
	Role            int16
	IsDeleted       pgtype.Bool
	CreateTimestamp pgtype.Timestamp
	UpdateTimestamp pgtype.Timestamp
	DeleteTimestamp pgtype.Timestamp
	PasswordHash    string
}
